# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec47a8997538fb47d48af1f740105da9f6cdecfb4df16d552757a1627a2bd5b63a9391ef4008ec6fb2336d6099402ce51266d0a63ffc078bcca806f4501af4c8

test:
  secret_key_base: a18d251dca2fbb116caf9effdf8dfebfe759e94571485b4a3771d17271e043f5da4b21806fcab193e39b3996e021d7ebb55762327cd1c17149e6961ea17d6404

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
